### ISSUE TITLE
.mdw-toolbar__title acting wierd together with .mdw-textfield

### ISSUE THREAD

**Issue by RobinBertilsson** [clshortfuse/materialdesignweb#1]
Just realized that for some reason the search field on this page:
https://clshortfuse.github.io/materialdesignweb/search.html

Act's wierd (in the second example) when you're using the `.mdw-toolbar__title` together with `.mdw-textfield`. However, if you remove `.mdw-textfield` as the (first example) it works way better.

I'm not sure if it's a bug in the library itself or if it's a bug in the "docs-page".
But you should take a look at it.

My specs:
Chrome: v65
OS: MacOS High Sierra 10.13.3

**Comment by clshortfuse** [comment]
First bug report! Thanks!

It's a docs bug. `.mdw-toolbar__title` shouldn't have shared classes. `.mdw-textfield` should be a child element inside it.
